# Generated by Django 4.2.6 on 2023-10-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('price', models.FloatField(db_index=True, default=2.12345678912345)),
                ('dis', models.TextField(default='abcd')),
                ('abool', models.BooleanField(default=True)),
            ],
        ),
    ]
