# Generated by Django 4.2.6 on 2023-10-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=130)),
                ('name', models.CharField(max_length=130)),
                ('password', models.CharField(max_length=130)),
            ],
        ),
    ]
