# Generated by Django 4.2.6 on 2023-11-02 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component1', '0003_userdata_confimr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='confimr',
            new_name='confirm',
        ),
    ]
